/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mercadona.mbordoya.web.main.kafka.producer.kafka_models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ExampleKafkaValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6881689908210082492L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExampleKafkaValue\",\"namespace\":\"com.mercadona.mbordoya.web.main.kafka.producer.kafka_models\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"typeId\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ExampleKafkaValue> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExampleKafkaValue> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ExampleKafkaValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ExampleKafkaValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ExampleKafkaValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ExampleKafkaValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ExampleKafkaValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ExampleKafkaValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ExampleKafkaValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.String name;
  private long typeId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExampleKafkaValue() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param typeId The new value for typeId
   */
  public ExampleKafkaValue(java.lang.Long id, java.lang.String name, java.lang.Long typeId) {
    this.id = id;
    this.name = name;
    this.typeId = typeId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return typeId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: typeId = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'typeId' field.
   * @return The value of the 'typeId' field.
   */
  public long getTypeId() {
    return typeId;
  }


  /**
   * Sets the value of the 'typeId' field.
   * @param value the value to set.
   */
  public void setTypeId(long value) {
    this.typeId = value;
  }

  /**
   * Creates a new ExampleKafkaValue RecordBuilder.
   * @return A new ExampleKafkaValue RecordBuilder
   */
  public static com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder newBuilder() {
    return new com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder();
  }

  /**
   * Creates a new ExampleKafkaValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExampleKafkaValue RecordBuilder
   */
  public static com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder newBuilder(com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder other) {
    if (other == null) {
      return new com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder();
    } else {
      return new com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder(other);
    }
  }

  /**
   * Creates a new ExampleKafkaValue RecordBuilder by copying an existing ExampleKafkaValue instance.
   * @param other The existing instance to copy.
   * @return A new ExampleKafkaValue RecordBuilder
   */
  public static com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder newBuilder(com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue other) {
    if (other == null) {
      return new com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder();
    } else {
      return new com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for ExampleKafkaValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExampleKafkaValue>
    implements org.apache.avro.data.RecordBuilder<ExampleKafkaValue> {

    private long id;
    private java.lang.String name;
    private long typeId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.typeId)) {
        this.typeId = data().deepCopy(fields()[2].schema(), other.typeId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ExampleKafkaValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.typeId)) {
        this.typeId = data().deepCopy(fields()[2].schema(), other.typeId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'typeId' field.
      * @return The value.
      */
    public long getTypeId() {
      return typeId;
    }


    /**
      * Sets the value of the 'typeId' field.
      * @param value The value of 'typeId'.
      * @return This builder.
      */
    public com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder setTypeId(long value) {
      validate(fields()[2], value);
      this.typeId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'typeId' field has been set.
      * @return True if the 'typeId' field has been set, false otherwise.
      */
    public boolean hasTypeId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'typeId' field.
      * @return This builder.
      */
    public com.mercadona.mbordoya.web.main.kafka.producer.kafka_models.ExampleKafkaValue.Builder clearTypeId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExampleKafkaValue build() {
      try {
        ExampleKafkaValue record = new ExampleKafkaValue();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.typeId = fieldSetFlags()[2] ? this.typeId : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExampleKafkaValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExampleKafkaValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExampleKafkaValue>
    READER$ = (org.apache.avro.io.DatumReader<ExampleKafkaValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeLong(this.typeId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString();

      this.typeId = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString();
          break;

        case 2:
          this.typeId = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










